### ISSUE TITLE
Exception NoSuchMethodError when using selenium 3.6.0

### ISSUE THREAD

**Issue by odemkovych** [serenity-bdd/serenity-core#953]
The latest selenium 3.6.0 changed signature (return value) of the ChromeOptions.addArguments method. That produce next error when serenity tries to call it:
net.serenitybdd.core.exceptions.SerenityManagedException: org.openqa.selenium.chrome.ChromeOptions.addArguments([Ljava/lang/String;)V

I think to fix it is needed to release new version compiled with selenium 3.6.0

**Comment by wakaleo** [comment]
Serenity 1.6.4 will be build with Selenium 3.6 - should be released in the next few days

**Comment by wakaleo** [comment]
Selenium 3.6.0 has a number of major bugs, so we are waiting for the next Selenium release to upgrade.
