### ISSUE TITLE
Facing java.lang.NoClassDefFoundError: org/apache/maven/surefire/booter/SurefireExecutionException after changing serenity version 2.0.60 to 2.0.63

### ISSUE THREAD

**Issue by gohilniks** [serenity-bdd/serenity-core#2593]
I'm using older version of serenity and working fine with the serenity-core version 2.0.60 but this version not supporting LoggingPrefs so just needs to change version to 2.0.63. But getting the error as follows:
`java.lang.NoClassDefFoundError: org/apache/maven/surefire/booter/SurefireExecutionException`

I have updated the serenity related dependencies and also tried some different solutions but not able to resolve this. 
My pom.xml is as follows :

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <groupId>test-suite</groupId>
    <artifactId>test-suite</artifactId>
    <version>1.0-SNAPSHOT</version>
    <modelVersion>4.0.0</modelVersion>
    <name>Test</name>
    <description>test cases verification</description>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.core.version>2.0.63</serenity.core.version>
        <serenity.junit.version>2.0.63</serenity.junit.version>
        <serenity.cucumber.version>1.9.29</serenity.cucumber.version>
        <serenity.maven.version>2.0.63</serenity.maven.version>
        <webdriver.driver>chrome</webdriver.driver>
        <bs.version>0.4</bs.version>
        <log4j.version>1.2.17</log4j.version>
        <slf4j.version>1.6.1</slf4j.version>
        <junit.version>4.12</junit.version>
        <assert.version>1.7.0</assert.version>
        <maven.compiler.version>3.2</maven.compiler.version>
        <maven.failsafe.version>2.21.0</maven.failsafe.version>
        <serenity.emailer.version>2.0.7</serenity.emailer.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>${log4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.1</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.1</version>
        </dependency>

        
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.23</version>
        </dependency>
        <dependency>
            <groupId>org.ini4j</groupId>
            <artifactId>ini4j</artifactId>
            <version>0.5.4</version>
        </dependency>

        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.core.version}</version>
        </dependency>

        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.junit.version}</version>
        </dependency>

        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
        </dependency>

        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.core.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assert.version}</version>
            <scope>test</scope>
        </dependency>

        
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
            <version>1.6.2</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.version}</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>

            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>${serenity.core.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            
            <id>TestLocal</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>${maven.failsafe.version}</version>
                        <configuration>
                            <includes>
                                <include>TestRunner.java</include>
                            </includes>
                            <rerunFailingTestsCount>0</rerunFailingTestsCount>
                            <forkCount>0</forkCount>
                            <reuseForks>true</reuseForks>
                            <systemPropertyVariables>
                                <chrome_preferences.download.default_directory>${user.dir}\config\Files
                                </chrome_preferences.download.default_directory>
                                <webdriver.driver>${webdriver.driver}</webdriver.driver>
                                <webdriver.chrome.driver>config/googlechrome/windows/chromedriver.exe
                                </webdriver.chrome.driver>
                            </systemPropertyVariables>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
</project>`
