### ISSUE TITLE
Tests are not executed anymore

### ISSUE THREAD

**Issue by awallat** [serenity-bdd/serenity-core#318]
Since version 1.1.25-rc.5 none of my tests can be executed anymore. Normally I can execute my jUnit style Serenity-BDD Tests within Eclipse, but now it immediately stops without any error information. No browser comes up. With rc.4 everything still works. My TestClass look like this:

```java
@RunWith(SerenityRunner.class)
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class IPlugExcel {

    @WithTags({ @WithTag(type = "feature", name = "myFeatureName"), @WithTag(type = "capability", name = "myCapabilityName") })
    @Title("Do some testing here")
    @Test
    public void excel01_someTest() {
      // ...
    }
}
```

**Output:**
```
209 [main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - project.build.directory : null
210 [main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - project.reporting.OutputDirectory : null
210 [main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - OutputDirectory : C:\Projects\selenium\ingrid-serenity-tests\target\site\serenity
219 [main] INFO net.serenitybdd.core.Serenity - 

####
SERENITY-LOGO
####

236 [main] INFO net.serenitybdd.core.Serenity - Test Suite Started: I plug excel
```

Anyone any idea? Thanks!

**Comment by YamStranger** [comment]
Hello @awallat 

Thanks for this issue, yes some updates was in [v1.1.25-rc.5](https://github.com/serenity-bdd/serenity-core/releases/tag/v1.1.25-rc.5) and same functionality was changed in [v1.1.25-rc.6](https://github.com/serenity-bdd/serenity-core/releases/tag/v1.1.25-rc.6). 

Please try run your code with v1.1.25-rc.6 and for sure we will help you ). 

Also, did you try to run your tests with latest version of serenity libs? 

Thanks!

**Comment by awallat** [comment]
This version is unfortunately not in the maven-repository where we get our libs. But we also tried the latest version [v1.1.26](https://github.com/serenity-bdd/serenity-core/releases/tag/v1.1.26) and have the same issue.

When we set this version in our pom.xml we automatically get the latest version of the serenity libs.

Thanks for helping!

**Comment by YamStranger** [comment]
@awallat this version can be find in 
```
   <repositories>
      <repository>
        <snapshots>
        <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray</name>
        <url>http://jcenter.bintray.com</url>
      </repository>
    </repositories>
    <pluginRepositories>
      <pluginRepository>
        <snapshots>
        <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray-plugins</name>
        <url>http://jcenter.bintray.com</url>
      </pluginRepository>
    </pluginRepositories>
```

Can you put here your pom, I will try to reproduce your problem (based on example that you provided). For now I have several examples of tests with @managed webdriver - and it works fine... 

Thanks!

**Comment by joekeen** [comment]
I appear to be having the same issue after upgrading to 1.1.26. 

There is an error in the debug output:

```
2016-02-23 10:43:16,215 DEBUG Darkroom Opening darkroom
2016-02-23 10:43:16,215 DEBUG DarkroomProcessingLine Darkroom processing line starting up
2016-02-23 10:43:16,247 INFO Serenity 
2016-02-23 10:43:16,641 DEBUG RetryFilteringRunNotifier Test failed: xxx: net.serenitybdd.junit.runners.SerenityRunner.isIgnored(Lorg/junit/runners/model/FrameworkMethod;)Z
java.lang.NoSuchMethodError: net.serenitybdd.junit.runners.SerenityRunner.isIgnored(Lorg/junit/runners/model/FrameworkMethod;)Z
	at net.serenitybdd.junit.runners.SerenityRunner.processTestMethodAnnotationsFor(SerenityRunner.java:501)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:431)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:246)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
2016-02-23 10:43:17,392 INFO Serenity Test Suite Started: When xxx
2016-02-23 10:43:17,392 DEBUG Darkroom Closing darkroom
2016-02-23 10:43:17,392 DEBUG DarkroomProcessingLine Darkroom processing line shutting down
```

Tests were working with 1.1.25-rc2, have not tried any other release candidates between rc2 and 1.1.26.

**Comment by joekeen** [comment]
Looks to broken since rc5 via: https://github.com/serenity-bdd/serenity-core/commit/2e2450a32770d5e0f2c906f3886372a705df01a0.

**Comment by YamStranger** [comment]
@joekeen your problem sounds like version conflict. Please add here your pom or gradle build to help you, for now I can not reproduce your problem. 

To test build with 1.1.26 I use some test projects, you can try to build it as well to be sure that all works fine: where is reference to repository on specific commit ([web-todomvc-tests](https://github.com/serenity-bdd/serenity-test-projects/tree/2985fbd39d636dfda3cfbdb0d04cddb10778be32/web-todomvc-tests))

Please try to check out it, init submodules and run ` ./gradlew clean test aggregate`. As result test against todomvc.com](http://todomvc.com/) will be executed. These tests are used chrome and firefox as well so chrome should be in your class path. 

As result tests are executed and report is build :
![image](https://cloud.githubusercontent.com/assets/1667699/13242821/6d64a39a-da01-11e5-9b7f-478ef3894740.png)

**Comment by YamStranger** [comment]
@awallat I created test as you described, here is code: 

```
...
import net.serenitybdd.junit.runners.SerenityRunner;
import net.thucydides.core.annotations.Managed;
import net.thucydides.core.annotations.Title;
import net.thucydides.core.annotations.WithTag;
import net.thucydides.core.annotations.WithTags;
import org.junit.Assert;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.WebDriver;

@RunWith(SerenityRunner.class)
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class IPlugExcel {

    @Managed
    WebDriver jane;


    @WithTags({ @WithTag(type = "feature", name = "myFeatureName"), @WithTag(type = "capability", name = "myCapabilityName") })
    @Title("Do some testing here")
    @Test
    public void excel01_someTest() {
        jane.get("https://www.google.com.ua");
        Assert.assertTrue(jane.getCurrentUrl().contains("www.google.com"));
    }
}
```
main dependencies version:  
```
    serenityCoreVersion = "1.1.26"
    serenityJBehaveVersion = "1.6.0"
    serenityCucumberVersion = "1.1.5"
```

full dependency of build here: [dependecyTree.txt](https://github.com/serenity-bdd/serenity-core/files/142000/dependecyTree.txt)
test executed successfully and all works fine. Google opened as browser as well, also I generated report for you: 
![do_something_here](https://cloud.githubusercontent.com/assets/1667699/13243123/a5823c3a-da04-11e5-903f-85859c9bc6dc.png)

@awallat I can not reproduce your bug, provided test structure works fine. Please add more details, core, build file, etc. From my side all looks fine

**Comment by joekeen** [comment]
@YamStranger you are right, we must be on an old version of JUnit before this change: https://github.com/junit-team/junit/commit/5cdd702717c5ca7dd3002e95847232681c445127. Apologies for adding noise to this issue.

**Comment by awallat** [comment]
Thanks @YamStranger  and @joekeen!!!

We were using jUnit v4.11, which seemed to be incompatible with the latest serenity version. I removed the dependency to jUnit from our pom.xml, since it's automatically set by the serenity-junit-library. With jUnit v4.12 the tests run again.

I'll close this ticket now.

**Comment by YamStranger** [comment]
@joekeen don't worry, I glad to help you ) 

@awallat unfortunately some times such type of errors quite difficult to find...

Thanks for helping us to make Serenity BDD better!
