### ISSUE TITLE
Serenity Devtools driver issue

### ISSUE THREAD

**Issue by Vijay2871** [serenity-bdd/serenity-core#2925]
When i try to extract info from console using devtools I'm getting issue in driver showing null
code snippet: 
![image](https://user-images.githubusercontent.com/54226136/190545629-7bb675b0-914f-40b8-aa42-553e5427d4ce.png)

Error:Step failed
java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.devtools.DevTools.createSession()" because "this.devTools" is null

![image](https://user-images.githubusercontent.com/54226136/190545474-aaa5218f-4f3f-4a72-ad55-42503fd47795.png)

**Comment by globalworming** [comment]
you are just declaring `Devtools devtools;`, they are just `null`. you have to get devtools from the webdriver like [here](https://github.com/globalworming/serenity-junit-screenplay-starter/blob/main/src/test/java/com/example/e2e/browser/Selenium4FeaturesIT.java#L43)

though in step libraries you don't get the webdriver, do you?

**Comment by oleksandrkobzan** [comment]
hi @globalworming, 
I have the same result running tests on [docker-selenium](https://github.com/SeleniumHQ/docker-selenium) 4.5.0-20221004 version.
Browser: chrome

BrowseTheWeb.as(actor).getDevTools() is returned null.

**Comment by wakaleo** [comment]
getDevTools() will return null if the driver does not support the `HasDevTools` interface - are you sure the driver you are using supports dev tools?

**Comment by oleksandrkobzan** [comment]
Hi @wakaleo,
It doesn't work on serenity core 3.3.4,3.3.5, but works on 3.2.5
Our configuration is:
- setup selenium hub and node with Chrome and pass parameters 
-Dwebdriver.remote.url=http://localhost:4444/wd/hub 
-Dwebdriver.driver=chrome

Works when run on local driver for all versions 
-Dwebdriver.chrome.driver=/home/user/Downloads/chromedriver

**Comment by wakaleo** [comment]
Can you propose a PR if you can see something wrong?

**Comment by wakaleo** [comment]
Cool, so this can be closed?

**Comment by oleksandrkobzan** [comment]
please don't close it because the issue with RemoteWebDriver still exists.

**Comment by wakaleo** [comment]
This isn't a Serenity issue. The `RemoteWebDriver` class does not implement the `HasDevTools` interface, and so cannot provide a DevTools object.  The DevTools support works correctly for drivers that implement `HasDevTools`, e.g.

```java
        BrowseTheWeb.as(actor).maybeGetDevTools().ifPresent(
                devTools -> {
                    devTools.createSession();
                    devTools.send(Log.enable());
                    devTools.addListener(Log.entryAdded(), logEntry -> {
                        System.out.printf("DEVTOOLS LOG: %s\n - %s: %s",logEntry.getLevel(), logEntry.getUrl(), logEntry.getText());
                    });
                }
        );
```
