### ISSUE TITLE
Upgrading to version 2.4.x

### ISSUE THREAD

**Issue by frostrider33** [serenity-bdd/serenity-core#2463]
Hi everybody,

When upgrading my serenity-bdd-core from 2.3.10 to 2.4.0, i have this error :

java.lang.IncompatibleClassChangeError: Class net.thucydides.core.steps.construction.StepLibraryType$2 does not implement the requested interface java.util.function.Predicate

Even if I remove my .m2 cache.

Any idea ?

**Comment by wakaleo** [comment]
Sound's like a version conflict.

**Comment by frostrider33** [comment]
It seems yes but .. which one ? :)

Is there a specific mapping

**Comment by wakaleo** [comment]
https://github.com/serenity-bdd/serenity-core/blob/master/README.md#what-is-the-latest-stable-version-i-should-use

**Comment by frostrider33** [comment]
Thanks for your help but still have the problem ... i will investigate ... ;)

**Comment by frostrider33** [comment]
The conflict was with one of our internal component. Problem solved. Thanks for your help.
