### ISSUE TITLE
There is one typo about serenity-cucumber4 version for the Cucumber 4 support.

### ISSUE THREAD

**Issue by applehorse** [serenity-bdd/serenity-core#1894]
Hi There,

Maybe there is a typo on the below page for the Cucumber 4 support:
https://github.com/serenity-bdd/serenity-core/blob/master/README.md#serenity-with-junit

Currently, it's 
serenity-core | serenity-maven-plugin | serenity-cucumber4 | Cucumber
-- | -- | -- | --
2.0.84 | 2.0.84 | 1.0.22 | 4.2.0

Actually,
2.0.84 can only work with 1.0.21 in my local.

When I run 2.0.84 with 1.0.22, I got the below error:
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.058 s <<< FAILURE! - in com.TEST.testRunners.TestRunners
[ERROR] initializationError(com.TEST.testRunners.TestRunners)  Time elapsed: 0.013 s  <<< ERROR!
java.lang.NoClassDefFoundError: io/cucumber/core/options/FeatureOptions
Caused by: java.lang.ClassNotFoundException: io.cucumber.core.options.FeatureOptions

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   TestRunners.initializationError » NoClassDefFound io/cucumber/core/options/Fea...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

It would be great if you could double-check on your side?

Cheers.
Will
