### ISSUE TITLE
ClassCastException when remote webdriver is used

### ISSUE THREAD

**Issue by ufroehling** [serenity-bdd/serenity-core#1236]
After upgrading Serenity from 1.8.11 to 1.9.13 I get ClassCastExceptions when I start my testsuite with remote webdriver configuration.

I have a test class with 3 tests. The first test passes and before the second test is executed, the exception is thrown. Unfortunately I could not trace it down to a certain release. As far as i could find out, the problems started with 1.8.13 but not a hard exception.

It only happens when using the remote Selenium grid, not the local driver directly. My command line is -Dwebdriver.driver=firefox-Dwebdriver.remote.url=http://gridmachine:4444/wd/hub -Dwebdriver.base.url="http://appserver:8080"

We use java with a base test class from which every test class inherits
```
    @Managed(uniqueSession = true)
    protected WebDriver driver;

    @ManagedPages
    public Pages pages;

    @Before
    public void setUp() throws Exception {
        driver.manage().window().setSize(new Dimension(1440, 1200));
```
  
Stacktrace: 
```
  TEST PASSED: Should show internal server error page
   ----------------------------------------------------------------------------

kn.myapp.visco.publicaccess.application.ErrorPageWebTest > classMethod STARTED
kn.myapp.visco.publicaccess.application.ErrorPageWebTest > classMethod FAILED
     java.lang.ClassCastException: net.thucydides.core.configuration.SystemPropertiesConfiguration cannot be cast to net.thucydides.core.webdriver.DriverConfiguration
         at net.thucydides.core.webdriver.SerenityWebdriverManager.withProperty(SerenityWebdriverManager.java:102)
         at net.thucydides.core.annotations.RequestedDrivers.requestedDriverFor(RequestedDrivers.java:44)
         at net.thucydides.core.annotations.TestCaseAnnotations.requestedDriverFrom(TestCaseAnnotations.java:71)
         at net.thucydides.core.annotations.TestCaseAnnotations.injectDrivers(TestCaseAnnotations.java:60)
         at net.serenitybdd.junit.runners.SerenityRunner.injectDriverInto(SerenityRunner.java:574)
         at net.serenitybdd.junit.runners.SerenityRunner.methodInvoker(SerenityRunner.java:551)
         at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:273)
         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
         at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:460)
         at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:435)
         at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:42)
         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
         at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:239)
         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:116)
```

**Comment by cliviu** [comment]
Hi @ufroehling, can you please provide a small test program to help me reproduce your issue ?

**Comment by ufroehling** [comment]
Thanks, will check your possible fix

**Comment by volnoboy** [comment]
I have tried to update from 1.9.6 to 1.9.16 version and I get the same exception. Even without using the remote driver.  

java.lang.IllegalArgumentException: Can not set net.thucydides.core.webdriver.DriverConfiguration field net.serenitybdd.jbehave.SerenityStories.systemConfiguration to net.thucydides.core.configuration.SystemPropertiesConfiguration

	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at net.serenitybdd.core.injectors.EnvironmentDependencyInjector.injectSysConfigVariables(EnvironmentDependencyInjector.java:59)
	at net.serenitybdd.core.injectors.EnvironmentDependencyInjector.injectDependenciesInto(EnvironmentDependencyInjector.java:36)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:28)
	at net.serenitybdd.jbehave.SerenityStepFactory.injectDependencies(SerenityStepFactory.java:85)
	at net.serenitybdd.jbehave.SerenityStepFactory.createInstanceOfType(SerenityStepFactory.java:75)
	at org.jbehave.core.steps.StepCreator.stepsInstance(StepCreator.java:97)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:743)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:351)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1163)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:1030)
	at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:1061)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:965)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:869)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:845)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:427)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:398)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wakaleo** [comment]
Are you using the latest serenity-jbehave version (1.40.0)?

**Comment by volnoboy** [comment]
Yes

**Comment by wakaleo** [comment]
It could be some kind of dependency conflict - can you provide a sample project?

**Comment by volnoboy** [comment]
Here is the link to zip with project: https://www.sendspace.com/file/1hb1ai

**Comment by ufroehling** [comment]
For me the problem is solved. No ClassCast Exceptions anymore with 1.9.14. Many thanks again @cliviu

**Comment by volnoboy** [comment]
Should I open a new issue? Because my issue is in 1.9.16. Did you reproduce it in my sample project?

**Comment by wakaleo** [comment]
Does your version work with 1.9.14?

**Comment by volnoboy** [comment]
No, I still get the same exception. If I change jbehave to 1.38.0, I get:


 java.lang.NoSuchMethodError: net.thucydides.core.webdriver.Configuration.getDriverType()Lnet/thucydides/core/webdriver/SupportedWebDriver;

**Comment by wakaleo** [comment]
Have you done a dependency analysis to see what Serenity libraries are being included?

**Comment by volnoboy** [comment]
I tried to, tell me what should I look for specifically. I get exception even when I removed all my extra dependencies. Latest versions where everything works are 1.9.12 and jbehave 1.38.0

**Comment by volnoboy** [comment]
This problem is fixed for me in 1.9.17. Thank you!
