### ISSUE TITLE
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found 

### ISSUE THREAD

**Issue by SchnuckySchuster** [serenity-bdd/serenity-core#2643]
With Serenity 3.1.10 I get the following error Message

`rg.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/Users/gerhardschuster/Entwicklung/java/Serenity-BDD-Screenplay-Example-with-Cucumber/target/classes]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
    at org.reflections.vfs.Vfs.fromURL (Vfs.java:113)
    at org.reflections.vfs.Vfs.fromURL (Vfs.java:95)
    at org.reflections.Reflections.lambda$scan$2 (Reflections.java:176)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:183)
    at java.util.HashMap$KeySpliterator.forEachRemaining (HashMap.java:1707)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:509)
    at java.util.stream.ForEachOps$ForEachTask.compute (ForEachOps.java:290)
    at java.util.concurrent.CountedCompleter.exec (CountedCompleter.java:754)
    at java.util.concurrent.ForkJoinTask.doExec (ForkJoinTask.java:373)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec (ForkJoinPool.java:1182)
    at java.util.concurrent.ForkJoinPool.scan (ForkJoinPool.java:1655)
    at java.util.concurrent.ForkJoinPool.runWorker (ForkJoinPool.java:1622)
    at java.util.concurrent.ForkJoinWorkerThread.run (ForkJoinWorkerThread.java:165)`

<img width="1477" alt="image" src="https://user-images.githubusercontent.com/3406054/146528622-dd3bf13b-468a-461f-a680-8ef5ccce131e.png">

I'm working on a MacBook Pro with M1 Pro Chip and the latest Version of the OS.

You can use this project in order to reproduce the error message https://github.com/SchnuckySchuster/Serenity-BDD-Screenplay-Example-with-Cucumber

Is this of any concern?
Is my pom.xml wrong?

**Comment by wakaleo** [comment]
I had a look and I really have no idea.

**Comment by SchnuckySchuster** [comment]
I can not offer Help but a new observation.
When updating to 3.1.15 the test does not start due to a compilation error
<img width="1767" alt="image" src="https://user-images.githubusercontent.com/3406054/149158957-851d7305-fe2d-4f41-a95c-3c374f3870ac.png">

I see this message in my McaBook but also on a Windows 10 Machine.
