### ISSUE TITLE
With serenity version 3.3.0 getting Failed to instantiate page (net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class io.appium.java_client.AppiumDriver)

### ISSUE THREAD

**Issue by remyanekkuth** [serenity-bdd/serenity-core#2933]
@wakaleo  

We are upgrading serenity version from 2.3.10 to 3.3.0 

with **version 3.3.0** : 

Failed to instantiate page (net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class io.appium.java_client.AppiumDriver)
	at net.thucydides.core.pages.PageFactory.thisPageObjectLooksDodgy(PageFactory.java:103)
	at net.thucydides.core.pages.PageFactory.createPageOfType(PageFactory.java:50)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:83)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:50)
	at net.serenitybdd.core.Serenity.injectDependenciesInto(Serenity.java:69)
	at net.serenitybdd.core.Serenity.initializeWithNoStepListener(Serenity.java:111)
	at cucumber.runtime.SerenityObjectFactory.newInstance(SerenityObjectFactory.java:76)
	at cucumber.runtime.SerenityObjectFactory.cacheNewInstance(SerenityObjectFactory.java:59)
	at cucumber.runtime.SerenityObjectFactory.getInstance(SerenityObjectFactory.java:49)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaHookDefinition.execute(JavaHookDefinition.java:64)
	at io.cucumber.core.runner.CoreHookDefinition.execute(CoreHookDefinition.java:46)
	at io.cucumber.core.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:21)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:85)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:78)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.lambda$run$0(PickleRunners.java:151)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions$$Lambda$258/601047778.accept(Unknown Source)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)
	at io.cucumber.core.runtime.CucumberExecutionContext$$Lambda$259/1015809068.run(Unknown Source)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:148)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:144)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:28)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at io.cucumber.junit.FeatureRunner.run(FeatureRunner.java:137)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:259)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:59)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:288)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:745)

**with version 2.3.10 : 

   mobile test is executing successfully** 

build.gradle dependencies :

   testImplementation (group: 'org.hamcrest',              name: 'hamcrest',                          version: '2.2')
//testImplementation		(group: 'maven.com.perfecto.reporting-sdk', name: 'reportium-java', 			version: '2.3')
//testImplementation		(group: 'maven.com.perfecto.reporting-sdk', name: 'reportium-import-java', 		version: '2.3')
//testImplementation		(group: 'maven.com.perfecto.reporting-sdk', name: 'reportium-testng', 			version: '2.3')
   testImplementation (group: 'net.serenity-bdd',          name: 'serenity-core',                     version: '3.3.0')
   testImplementation (group: 'net.serenity-bdd',          name: 'serenity-cucumber',                version: '3.3.0')
    testImplementation (group: 'net.serenity-bdd',          name: 'serenity-screenplay-webdriver',     version: '3.3.0')
    testImplementation (group: 'net.serenity-bdd',          name: 'serenity-ensure',                   version: '3.3.0')
    testImplementation (group: 'junit',                     name: 'junit',                             version: '4.13.1')
    testImplementation (group: 'org.apache.poi',            name: 'poi-ooxml',                         version: '4.1.2')

Any suggestions for fix.

Note : I tried couple of things. removed /wd/hub from appium.hub from serenity.properties
I also found extend PageObject with override apply() . both didn't work.

**Comment by wakaleo** [comment]
No idea - probably best to ask on the Gitter channel. Maybe related to the Appium version you have installed?

**Comment by aadhi00** [comment]
No. I think it's an issue with serenity. I even created a customer driver but it's not getting called during execution. Only success I had was with 3.1.15 but there also I am facing issue with initializing the page objects. I can share my code if it helps

**Comment by wakaleo** [comment]
Serenity doesn't do anything special during the driver creation. If you think it might  be a Serenity issue, have a look at the code and if you find anything you can always propose a PR. If it worked previously it's probably not related to your code. "Could not instantiate class io.appium.java_client.AppiumDriver" generally means there was an issue starting the driver (e.g. an incompatibility with the appium version you are using). It's generally not directly related to the Serenity code.

**Comment by aadhi00** [comment]
I found the issue, serenity is trying to fetch the window handle which is not supported by AppiumDriver. 

` When User enters "aadhithyan" and "12345678"                                    # com.atlasmobile.runner.LoginStepDefinitions.user_enters_and(java.lang.String,java.lang.String)
      org.openqa.selenium.UnsupportedCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'DESKTOP-LRTUTB1', ip: '192.168.1.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_292'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [5f0817bd-3f79-4d2e-8257-badb70682f62, getCurrentWindowHandle {}]
Capabilities {appium:app: C:\Users\aadhi\Downloads\an..., appium:appPackage: com.tuci.cibilindia, appium:automationName: UiAutomator2, appium:databaseEnabled: false, appium:desired: {app: C:\Users\aadhi\Downloads\an..., automationName: UiAutomator2, deviceName: samsung m31, platformName: android, platformVersion: 12.0, skipServerInstallation: true, udid: RZ8N715TCEF}, appium:deviceApiLevel: 31, appium:deviceManufacturer: samsung, appium:deviceModel: SM-M315F, appium:deviceName: RZ8N715TCEF, appium:deviceScreenDensity: 420, appium:deviceScreenSize: 1080x2340, appium:deviceUDID: RZ8N715TCEF, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:pixelRatio: 2.625, appium:platformVersion: 12, appium:skipServerInstallation: true, appium:statBarHeight: 78, appium:takesScreenshot: true, appium:udid: RZ8N715TCEF, appium:viewportRect: {height: 2053, left: 0, top: 78, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: 5f0817bd-3f79-4d2e-8257-badb70682f62
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:267)
	at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandle(RemoteWebDriver.java:465)
	at net.thucydides.core.webdriver.WebDriverFacade.getWindowHandle(WebDriverFacade.java:333)
	at net.serenitybdd.core.photography.WebDriverPhotoLens.alertIsDisplayedFor(WebDriverPhotoLens.java:43)
	at net.serenitybdd.core.photography.WebDriverPhotoLens.canTakeScreenshot(WebDriverPhotoLens.java:34)
	at net.serenitybdd.core.photography.PhotoSession.takeScreenshot(PhotoSession.java:47)
	at net.serenitybdd.core.photography.PhotoSessionBooking.takeScreenshot(PhotoSessionBooking.java:36)
	at net.thucydides.core.steps.BaseStepListener.screenshotFrom(BaseStepListener.java:1104)
	at net.thucydides.core.steps.BaseStepListener.lambda$grabScreenshots$9(BaseStepListener.java:1094)
	at net.thucydides.core.steps.BaseStepListener$$Lambda$802/0x0000000000000000.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:241)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at net.thucydides.core.steps.BaseStepListener.grabScreenshots(BaseStepListener.java:1096)
	at net.thucydides.core.steps.BaseStepListener.take(BaseStepListener.java:991)
	at net.thucydides.core.steps.BaseStepListener.takeEndOfStepScreenshotFor(BaseStepListener.java:972)
	at net.thucydides.core.steps.BaseStepListener.stepFailed(BaseStepListener.java:856)
	at net.thucydides.core.steps.StepEventBus.stepFailed(StepEventBus.java:495)
	at net.thucydides.core.steps.StepInterceptor.notifyOfStepFailure(StepInterceptor.java:552)
	at net.thucydides.core.steps.StepInterceptor.logStepFailure(StepInterceptor.java:476)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:468)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:209)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:196)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:84)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	at com.atlasmobile.steps.LoginSteps$ByteBuddy$WBEaEDsK.entersUsernameAndPassword(Unknown Source)
	at com.atlasmobile.runner.LoginStepDefinitions.user_enters_and(LoginStepDefinitions.java:24)
	at ✽.User enters "aadhi" and "aadhi"(file:///C:/Users/aadhi/IdeaProjects/atlas-mobile-automation/src/test/resources/features/Login.feature:5)
`

**Comment by wakaleo** [comment]
Well spotted - this will be fixed in the next release.

**Comment by remyanekkuth** [comment]
@wakaleo when can we expect the new version ? This issue is blocking us to proceed further with release

**Comment by wakaleo** [comment]
You can test this by creating a local snapshot version (run mvn install -DskipTests).

**Comment by taelus** [comment]
For what it's worth, I went ahead and pulled the SNAPSHOT down and compiled it in to the project instead. I'm still getting the same issue when using appium. Below is the stacktrace I see. Removing the HeaderView class (which ultimately extends PageObject) just has it point at a different View class. This happens in 3.3.5-SNAPSHOT as well as 3.3.2.

`The page object class [[removed]].HeaderView could not be instantiated:
Failed to instantiate page (net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class io.appium.java_client.AppiumDriver)
net.thucydides.core.pages.WrongPageError: The page object class [[removed]].HeaderView could not be instantiated:
Failed to instantiate page (net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class io.appium.java_client.AppiumDriver)
	at app//net.thucydides.core.pages.PageFactory.thisPageObjectLooksDodgy(PageFactory.java:103)
	at app//net.thucydides.core.pages.PageFactory.createPageOfType(PageFactory.java:54)
	at app//net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:83)
	at app//net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:50)
	at app//net.thucydides.core.steps.StepFactory.injectOtherDependenciesInto(StepFactory.java:206)
	at app//net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:196)
	at app//net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:177)
	at app//net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:124)
	at app//net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16)
	at app//net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:89)
	at app//net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:70)
	at app//net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:52)
	at app//net.serenitybdd.core.Serenity.injectScenarioStepsInto(Serenity.java:146)
	at app//net.serenitybdd.core.Serenity.initializeWithNoStepListener(Serenity.java:110)
	at app//cucumber.runtime.SerenityObjectFactory.newInstance(SerenityObjectFactory.java:76)
	at app//cucumber.runtime.SerenityObjectFactory.cacheNewInstance(SerenityObjectFactory.java:59)
	at app//cucumber.runtime.SerenityObjectFactory.getInstance(SerenityObjectFactory.java:49)
	at app//io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at app//io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at app//io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at app//io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at app//io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at app//io.cucumber.core.runner.TestStep.executeStep(TestStep.java:85)
	at app//io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at app//io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at app//io.cucumber.core.runner.TestCase.run(TestCase.java:84)
	at app//io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at app//io.cucumber.junit.PickleRunners$NoStepDescriptions.lambda$run$0(PickleRunners.java:151)
	at app//io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)
	at app//io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at app//io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)
	at app//io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:148)
	at app//io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:144)
	at app//io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:28)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at app//io.cucumber.junit.FeatureRunner.run(FeatureRunner.java:137)
	at app//io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:259)
	at app//io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:59)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:288)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.2/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)`

I went back to 2.6.0 for core and rest-assured and swapped to serenity-cucumber6  since serenity-cucumber didn't have a matching version at that point and picked up at 3.0.0. That's when this happened:

`[[removed]]/src/main/java/com/wfscorp/myWorldAutotest/views/SharedView.java:69: error: cannot access FindsByAndroidUIAutomator
        locationAllowWhileUsingAppOption.click();
                                        ^
  class file for io.appium.java_client.FindsByAndroidUIAutomator not found`

For whatever it's worth, I've always loved that you use the term "dodgy" in this tool, and I've been using it since it was Thucydides, enjoying that none of my coworkers could pronounce it correctly :-)

**Comment by wakaleo** [comment]
Appium support is community driven - if you can add a fix and propose a PR, it will go into the next release.

**Comment by tnabror** [comment]
@wakaleo this issue seems already resolved. got the same issue before, fixed after updating to 3.3.8.
thank youu

**Comment by gsangar** [comment]
I don't know if it's related or if I should open another issue but after upgrading from 3.2.5 to 3.4.2 we have the same issue as logged here but with ChromeDriver.

`net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver

	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:168)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:156)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:126)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:196)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:983)
	at net.serenitybdd.core.pages.PageObject.openUrl(PageObject.java:929)
	at net.serenitybdd.screenplay.actions.OpenUrl.performAs(OpenUrl.java:18)
	at net.serenitybdd.screenplay.actions.OpenUrl$ByteBuddy$pXOtouGA.performAs$accessor$FooKZ7xh(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:503)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:483)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:457)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:209)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:196)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:84)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	at net.serenitybdd.screenplay.actions.OpenUrl$ByteBuddy$pXOtouGA.performAs(Unknown Source)
	at net.serenitybdd.screenplay.Actor.performTask(Actor.java:283)
	at net.serenitybdd.screenplay.Actor.perform(Actor.java:262)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:203)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:210)`
	
	
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: WebDriver was unable to create a new instance of type class org.openqa.selenium.chrome.ChromeDriver
WebDriver reported the following message: Remote driver not specified

The same code is working just fine in 3.2.5. 

Best regards

**Comment by wakaleo** [comment]
> I don't know if it's related or if I should open another issue but after upgrading from 3.2.5 to 3.4.2 we have the same issue as logged here but with ChromeDriver.
> 
> `net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
> 
> ```
> at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:168)
> at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:156)
> at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:126)
> at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:196)
> at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:983)
> at net.serenitybdd.core.pages.PageObject.openUrl(PageObject.java:929)
> at net.serenitybdd.screenplay.actions.OpenUrl.performAs(OpenUrl.java:18)
> at net.serenitybdd.screenplay.actions.OpenUrl$ByteBuddy$pXOtouGA.performAs$accessor$FooKZ7xh(Unknown Source)
> at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> at java.base/java.lang.reflect.Method.invoke(Method.java:577)
> at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:503)
> at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:483)
> at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:457)
> at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:209)
> at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:196)
> at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:84)
> at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
> at net.serenitybdd.screenplay.actions.OpenUrl$ByteBuddy$pXOtouGA.performAs(Unknown Source)
> at net.serenitybdd.screenplay.Actor.performTask(Actor.java:283)
> at net.serenitybdd.screenplay.Actor.perform(Actor.java:262)
> at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:203)
> at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:210)`
> ```
> 
> Caused by: net.thucydides.core.webdriver.DriverConfigurationError: WebDriver was unable to create a new instance of type class org.openqa.selenium.chrome.ChromeDriver WebDriver reported the following message: Remote driver not specified
> 
> The same code is working just fine in 3.2.5.
> 
> Best regards

Have you specified the remote driver using the webdriver.remote.driver property?
